### ISSUE TITLE
launchctl: Add macOS support

### ISSUE THREAD

**Issue by reportaman** [joehillen/sysz#11]
macOS uses launchctl instead of systemctl, please consider adding support for that :)

**Comment by joehillen** [comment]
I don't own a Mac and I never will. 

Everything in sysz is systemd specific, so it won't make sense for launchctl. I think this would be better served by a different tool. Feel free to use this as inspiration.

**Comment by aiotter** [comment]
@joehillen Is there a possibility of accepting PR for `launchctl`?

I'm in need of TUI daemon management tool and just found `sysz`. It looks great. The only problem is that I use both linux and macOS, and I don't want to introduce different tool for `launchctl` and `systemctl`.
It seems `sysz` is simple and I believe I can extend it with `launchctl`. If you feel okay, I'll try to add `launchd` support on `sysz` instead of just forking and rewriting all the `systemctl` commands to `launchctl` commands.
